name: OpenDeadlock
description: OpenDeadlock is a fan project inspired by the classic turn-based strategy game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  file_selector_macos: ^0.9.5
  file_selector: ^1.1.0
  file_selector_windows: ^0.9.3+5
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/images/terrain/
     - docs/reference/legacy-screenshots/nick-2026-06-27/
